services:
  - type: web
    name: flex-payment-research
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
